name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Launch python script to add values to the environment variables
      id: get-values
      run: |
        pip install requests
        python3 script.py
      shell: bash
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: 
        ./gradlew build
    
    - name: Remove previous release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: ${{ steps.get-values.outputs.LATEST_TAG }}
        delete_release: true

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        commitish: ${{ steps.get-values.outputs.LAST_COMMIT_HASH }}
        body: |
          ## Changelog
          ${{ steps.get-values.outputs.CHANGELOG }}
        release_name: ${{ steps.get-values.outputs.VERSION_NAME }} (build ${{ steps.get-values.outputs.LAST_COMMIT_HASH }})
        tag_name: ${{ steps.get-values.outputs.VERSION_NAME }}
    - name: Upload APK
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: app.apk
        asset_content_type: application/vnd.android.package-archive
      