name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Launch python script to add values to the environment variables
      run: |
        pip install requests
        python3 script.py
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: 
        ./gradlew build
    
    - name: Remove previous release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: ${{ env.LAST_TAG }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true

    - name: Create release and upload APK
      uses: actions/create-release@v1
      with:
        artifacts: app/build/outputs/apk/release/app-release.apk
        body: |
          ## Changelog
          ${{ env.CHANGELOG }}
        make_latest: true
        name: ${{ env.VERSION_NAME }} (build ${{ env.LAST_COMMIT_HASH }})
        tag_name: ${{ env.TAG_NAME }}
        token: ${{ secrets.TOKEN }}
        